# Example GitHub Actions workflow to build and publish the viewer static site.
#
# Standalone viewer repo: uses artifact path _site (default below).
# Consumer repo (after vendoring via subtree): change the "path" under
#   "Upload artifact" to viewer/_site so Pages publishes the viewer output.
#
name: Deploy viewer to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full clone so step-* git tags are available for integrated build

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install root dependencies
        run: npm ci

      - name: Install viewer-app dependencies
        run: npm ci --prefix viewer/viewer-app

      - name: Build full static site
        env:
          VIEWER_PAGES_URL: /${{ github.event.repository.name }}
        run: npm run build:pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: viewer/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
